spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
async:
  appid: 'async.send'
  solr:
    queue: 'solr.queue'
  basex:
    queue: 'basex.queue'

logging:
  level:
    org.springframework.amqp: info